### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by apiotuch** [AppInstaller/OptionalPackageSample#1]
Please make a c# example. I do not have admin rights for my work machine, and it is a constant hassle to get an admin to install visual studio packages to get samples to compile and run. This time c++ dev tools.

I have already needed 3 separate installs in the past week for 3 different samples from official Microsoft resource links.  This is very time consuming and wastes company resources.

**Comment by sandeepgeorge** [comment]
I published a C++ sample as I had a developer ask for that. I will publish a C# sample soon.

**Comment by sandeepgeorge** [comment]
Please take a look at https://github.com/AppInstaller/FaceAnalysis. Note that the Visual Studio tooling does not allow creating a managed optional packages which requires me to create the optional package in C++. See this for the details - https://blogs.msdn.microsoft.com/appinstaller/2017/04/05/uwpoptionalpackages/

**Comment by harvinders** [comment]
@sandeepgeorge We can [now create C# optional package ](https://docs.microsoft.com/en-us/windows/msix/package/optional-packages-with-executable-code#c-optional-packages-with-executable-code-1) and an example would be very helpful. I am stuck at how to load the dll from the package in C#.
