### ISSUE TITLE
Activation check

### ISSUE THREAD

**Issue by JoernMueller** [AppInstaller/OptionalPackageSample#2]
Hi @sandeepgeorge 
thank you very much for your excellent articles on UWP DLCs and this source code. This is not really an issue but a question. One thing I so far could not get is the difference between ActivatableOptionalPackage and OptionalPackage. When I do a folder diff on them they seem to differ only regarding the project name and also in the main program I can not find any further checking. So it would be great if you could clarify on how the activation check is acually performed.

**Comment by sandeepgeorge** [comment]
Sure. The difference between the two is really in the manifest. I have listed out the difference in the readme.md file. Let me know if this is not clear.

OptionalPackage project is a content only optional package. It is an app that does not have an entry in applist. The ActivatableOptionalPackages demonstrates that you can build an optional package that has code in it that can be loaded by MyMainApp. It also has an applist entry which means that users can launch the optional package directly from Start.

**Comment by JoernMueller** [comment]
Thank you very much for your explanation. Seems that I just misunderstood what "activatable" refers to and was looking for some kind of ownership verfication that should be done by the AppStore interface.
